config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'welcome#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :welcome
    resources :likes
    resources :playlists
    resource  :comments  
    resource  :subscriptions do
      post '/update_subcription', to: 'subscriptions#update_subcription'
      get '/pay', to: 'subscriptions#pay'
    end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
   can :read, ActiveAdmin::Page, name: 'Dashboard'
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    if user.super_admin?
      can :manage, :all
    else
      can :manage, Post
      can :read, SubscribtionPlan
    end



  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

   enum role: [:super_admin, :base_admin]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts

	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	validates :text, presence: true
end

app/models/csv_db.rb
require 'csv'
class CsvDb
	 class << self
    def convert_save(model_name, csv_data)
      csv_file = csv_data.read
      CSV.parse(csv_file) do |row|
      target_model = model_name.classify.constantize
      new_object = target_model.new
      column_iterator = -1
      target_model.column_names.each do |key|
      column_iterator += 1
      unless key == "0" 
         value = row[column_iterator] 
         new_object.send "#{key}=", value      
         Category.create(name: value)
       end
        new_object.save
     end
    end
  end
 end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
	belongs_to :user
end

app/models/playlist.rb
class Playlist < ApplicationRecord
	 belongs_to :user
	 belongs_to :post

	 after_create :playlist

	 def playlist
	 	    UserMailer.with(playlist: self).playlist_email.deliver_later
	 end
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :admin_user
  belongs_to :category
  has_one_attached :video
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :playlists, dependent: :destroy
  has_many :users, through: :playlists

  enum post_type: [:audio, :video ]


  validates :image, :name, :description, :duration, :post_type, presence: true

  scope :post_enable, -> { where(disable: false) }
  
end

app/models/subscribtion_plan.rb
class SubscribtionPlan < ApplicationRecord
	has_many  :subscriptions
    has_many  :users, through: :subscriptions

   validates :name, :plan_type, :amount, :interval, presence: true
   validate  :cheack_interval_greatar_or_not, if: -> {self.plan_type == 'daily'}
   validates  :plan_type,  uniqueness: true
   enum plan_type: [:weekly, :monthly, :yearly ]
 
   after_validation :create_plan, 
		def create_plan
		  unless self.errors.any?
				razorpay = Payment::RazorpayPlan.new
				razorpay.create_plan(self)
		  end
		end	

		def cheack_interval_greatar_or_not
		  errors.add(:interval, "In daily plan can't be less then 7") if interval < 7
        end	
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user
	belongs_to :subscribtion_plan

	before_save :create_subscription

	def create_subscription
	  razorpay = Payment::RazorpayPlan.new
	  subscription = razorpay.create_subscription(self)
	  self.razorpay_subscription_id = subscription
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :playlists
  has_many :posts, through: :playlists
  has_many :subscriptions
  has_many :subscribtion_plans, through: :subscriptions


  after_create :usermailer
  def usermailer
    UserMailer.with(user: self).welcome_email.deliver_later
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @comment = current_user.comments.create(comment_params)
    redirect_to welcome_path(@comment.post) 
	end
  
  def destroy
    @comment = current_user.comments.find_by(comment_params)
    @comment.destroy
    redirect_to welcome_path(@comment.post) 
  end
  private
    def comment_params
      params.permit(:post_id, :text)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
    @post = Post.find_by(id: params["post_id"])
    @like = @post.likes.find_by(user_id: current_user.id)
    unless @like.present?
      @post.likes.create(user_id: current_user.id)
      @post.count = @post.count + 1
      @post.save
      respond_to do |format|
        format.html
        format.js {render 'create'}
      end
    else
      @like.destroy
      @post.count = @post.count - 1
      @post.save
      respond_to do |format|
        format.html
        format.js {render 'unlike'}
      end
    end
  end
  
end

app/controllers/ol.rb
a ="esdfg"
puts "#{a}#{"jkdl"}"

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
      subscription = current_user.subscriptions.last
      if subscription.present? &&subscription.razorpay_payment_id.present? && DateTime.now < subscription.end_time
          @category = Category.find_by(id: params["category_id"])
          if @category.present?
           @post=@category.posts.post_enable
         elsif params["name"].present? 
          @post =Post.post_enable.where('name like ?',"#{params["name"]}%")
        else
          @post = Post.post_enable
        end
     else
       flash.alert = "Please subscribe see all the posts"
       render 'pleasesubscribe'
    end
   end

   def show
    @post=Post.find_by(id:params[:id])  
    @post.video.attached?
    @post.video
   end 
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_list.html.erb
  <% @posts = @category.posts%>
  <% @posts = @posts.reject{|post| post.id == @post.id}%> <%# They are rejected after play video inside show bar %>
  <% @posts.each do |post| %> 
     <div class="text-black zoom hover p-3" style="width: 20rem">
       <%= link_to(image_tag(post.image, size: "300x200"),welcome_path(post)) %>
       <%= @category.name%> 
       </br> 
     </div> 
 <%end%>


     
         
         
           

  
  

app/views/welcome/create.js.erb
document.getElementById('themeSwitch').addEventListener('change', function(event){
  (event.target.checked) ? document.body.setAttribute('data-theme', 'dark') : document.body.removeAttribute('data-theme');
});

app/views/welcome/index.html.erb
 <body style="background: radial-gradient(black, transparent);">
</br><div class="container ">
  <% @post.each_slice(4) do |posts| %>
    <div class="row">
      <% posts.each do |post| %> 
        <div class="col-sm-3"></br>
         <div class="text-black zoom hover p-3" style="width: 20rem">
          <%= link_to(image_tag(post.image, size: "300x200"),welcome_path(post)) if post.image.attached?%></br> 
          <% if current_user.playlists.find_by(post: post.id).present?%>           
            <button class="btn btn-outline-secondary button mt-1 ">Added To  Playlist</button>
               <%else%>
           <button class="btn btn-outline-primary button mt-1 <%= "Add_#{post.id}" %>"> 
            <%= link_to 'Add to playlist',playlists_path(post_id: post),:method => :post, :remote => true %></button>
            <%end%>

          <% if current_user.likes.find_by(post: post.id).present?%>
            <%= link_to likes_path(post_id: post), :method => :post, :remote => true do%>
              <b class= "<%= "uncount_#{post.id}" %> "> <%= post.count %> </b>
             <i class="fa-solid fa-thumbs-up <%= "unlike_#{post.id}" %>"></i></br> 
             <% end %>
          <%else%>
            <%= link_to likes_path(post_id: post), :method => :post, :remote => true do %>
             <b class= "<%= "count_#{post.id}" %> "> <%= post.count %> </b>
             <i class="far fa-thumbs-up <%="like_#{post.id}" %> "></i> </br>
            <% end %>
          <% end %>
           <b><%=post.name %></b></br>
           <font size="2"> <%=Category.find_by(id:post.category_id).name%></font> 
         </div>
       </div>
      <% end %>
    </div>
  <% end %>

   <% if @post.blank? %>
     <div class="list-group">
       <a href="#" class="list-group-item list-group-item-action active" aria-current="true">
       <h5 class="mb-1 text-center">No post available </h5>
      </div>
     <%end%>
     
  </div>
  </body>

app/views/welcome/pleasesubscribe.html.erb
<head>
  <body class ="bg-dark">
<div class="container" style = "max-width: 850px;"> 
  <% flash.each do |type, msg| %>
   <div class="alert alert-info text-center">
     <%= msg %>
   </div>
  <% end %>
    </br>
  <div class="container" style="max-width: 55%;">
    <div class="card text-center" style="width: 30rem;">
      <div class="card-body ">
        <h5 class=" text-center">Select plan to subscribe</h5><br>
        <%= form_tag subscriptions_path, method: :post do  %>  
          <% plans = SubscribtionPlan.all%>
          <% plans.each do |plan| %>  
          <div style="padding: 20px;">
          <%= radio_button_tag :subscribtion_plan_id, plan.id%> <%= plan.plan_type%> | 
          <%= plan.amount.to_i%> INR  </div>
        <%end%> 
          <br>
          <button  class="btn btn-outline-secondary ">Subscribe</button>  
      </div>
      <%end%>
     </div>
    </div>
  </div>
</div>
</body>
</head>

app/views/welcome/show.html.erb
</br></br>

<div class="container-fluid  ">
  <div class="row">
   <div class="col"> 
    <%=video_tag url_for(@post.video), :size=>"1180x680", :controls =>true,preview: true if @post.video.attached? %>
           <% if current_user.playlists.find_by(post_id: @post).present?%>           
             <button class="btn btn-outline-secondary button mt-1 ">Added To  Playlist</button>
                <%else%>
            <button class="btn btn-outline-primary button mt-1 <%= "Add_#{@post.id}" %>"> 
            <%= link_to 'Add to playlist',playlists_path(post_id: @post),:method => :post, :remote => true %></button>
            <%end%>
          <% if current_user.likes.find_by(post_id: @post).present?%>

            <%= link_to likes_path(post_id: @post), :method => :post, :remote => true do %>
              <b class= "<%= "uncount_#{@post.id}" %> "> <%= @post.count %> </b>
             <i class="fa-solid fa-thumbs-up <%= "unlike_#{@post.id}" %>"></i></br> 
             <% end %>
          <%else%>
            <%= link_to likes_path(post_id: @post), :method => :post, :remote => true do %>

             <b class= "<%= "count_#{@post.id}" %> "> <%= @post.count %> </b>
             <i class="far fa-thumbs-up <%="like_#{@post.id}" %> "></i> </br>
            <% end %>
          <% end %>
       <%@category = Category.find_by(id:@post.category_id)%>  
         <b><%=@post.name %></b></br><font size="2"> <%= @category.name%></font>
        </br><%= render 'comments/comment' %>
       </div>
       
       <div class="col">
       <%=render 'list' %>

       </div>
  </div>
 </div>


    

              
                
                  